name: JMeter load kafka vtb

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        mv apache-jmeter-5.6.3 jmeter
        
    - name: Copy libs + JMX
      run: |
        mkdir -p jmeter/lib/ext
        wget -P jmeter/lib/ext/ https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.6.0/kafka-clients-3.6.0.jar
        cp lib/*.jar jmeter/lib/ext/ || echo "No lib folder"
        
    - name: Run JMX
      run: |
        ./jmeter/bin/jmeter -n -t Jmeter-scenario-vtb.jmx
